SELECT INICIO_TEMPORADA_P, DIVISION_P, EQUIPO, SUM(PUNTOS) AS PUNTOS_TOTALES, SUM(GOLES_RECIBIDOS) AS GOLES_RECIBIDOS
FROM (
    SELECT INICIO_TEMPORADA_P, DIVISION_P, EQUIPO_LOCAL AS EQUIPO, 3 AS PUNTOS, PUNTOS_VISITANTE AS GOLES_RECIBIDOS
    FROM PARTIDO
    WHERE PUNTOS_LOCAL > PUNTOS_VISITANTE
    UNION ALL
    SELECT INICIO_TEMPORADA_P, DIVISION_P, EQUIPO_VISITANTE AS EQUIPO, 3 AS PUNTOS, PUNTOS_LOCAL AS GOLES_RECIBIDOS
    FROM PARTIDO
    WHERE PUNTOS_VISITANTE > PUNTOS_LOCAL
    UNION ALL
    SELECT INICIO_TEMPORADA_P, DIVISION_P, EQUIPO_LOCAL AS EQUIPO, 1 AS PUNTOS, PUNTOS_VISITANTE AS GOLES_RECIBIDOS
    FROM PARTIDO
    WHERE PUNTOS_LOCAL = PUNTOS_VISITANTE
    UNION ALL
    SELECT INICIO_TEMPORADA_P, DIVISION_P, EQUIPO_VISITANTE AS EQUIPO, 1 AS PUNTOS, PUNTOS_LOCAL AS GOLES_RECIBIDOS
    FROM PARTIDO
    WHERE PUNTOS_VISITANTE = PUNTOS_LOCAL
)
GROUP BY INICIO_TEMPORADA_P, DIVISION_P, EQUIPO
ORDER BY INICIO_TEMPORADA_P ASC, DIVISION_P ASC, PUNTOS_TOTALES DESC, GOLES_RECIBIDOS ASC;

