SET TIMING ON
--EXPLAIN PLAN FOR
SELECT NOMBRE_CORTO, NOMBRE_E, CAPACIDAD FROM EQUIPO
JOIN ESTADIO ON NOMBRE_E = NOMBRE
WHERE CAPACIDAD < 50000
AND NOMBRE_CORTO IN (
	SELECT DISTINCT C1.EQUIPO
	FROM CLASIFICACION C1
	JOIN CLASIFICACION C2 ON C1.INICIO_TEMPORADA_P = C2.INICIO_TEMPORADA_P
	AND C1.DIVISION_P = C2.DIVISION_P
	AND (
		C2.PUNTOS_TOTALES > C1.PUNTOS_TOTALES 
		OR (
			C2.PUNTOS_TOTALES = C1.PUNTOS_TOTALES 
			AND C2.GOLES_RECIBIDOS < C1.GOLES_RECIBIDOS
		)
	)
	WHERE C1.DIVISION_P = '1'
	GROUP BY C1.INICIO_TEMPORADA_P, C1.EQUIPO
	HAVING COUNT(C2.EQUIPO) < 2
);
--SELECT PLAN_TABLE_OUTPUT FROM TABLE(DBMS_XPLAN.DISPLAY());
