SELECT INICIO_TEMPORADA_P, JORNADA, SUM(PUNTOS_LOCAL + PUNTOS_VISITANTE) AS PUNTOS_TOTALES
FROM PARTIDO
WHERE INICIO_TEMPORADA_P = (
 	SELECT MAX(INICIO_TEMPORADA_P)
    	FROM PARTIDO
)
AND DIVISION_P = '2'
GROUP BY JORNADA, INICIO_TEMPORADA_P
HAVING SUM(PUNTOS_LOCAL + PUNTOS_VISITANTE) = (
	SELECT MAX(TOTAL_G) AS PUNTOS_TOTALES
	FROM (
		SELECT SUM(PUNTOS_LOCAL + PUNTOS_VISITANTE) AS TOTAL_G
		FROM PARTIDO
		WHERE INICIO_TEMPORADA_P = (
			SELECT MAX(INICIO_TEMPORADA_P)
				FROM PARTIDO
		)
		AND DIVISION_P = '2'
		GROUP BY JORNADA
	)
);

