SELECT P1.INICIO_TEMPORADA_P, P1.DIVISION_P, COUNT(*) AS VICTORIAS_ZGZ
FROM PARTIDO P1
JOIN PARTIDO P2 ON P1.INICIO_TEMPORADA_P=P2.INICIO_TEMPORADA_P 
					AND P1.EQUIPO_LOCAL=P2.EQUIPO_VISITANTE 
					AND P1.EQUIPO_VISITANTE=P2.EQUIPO_LOCAL
WHERE P1.EQUIPO_LOCAL='Zaragoza' 
		AND P1.PUNTOS_LOCAL > P1.PUNTOS_VISITANTE 
		AND P2.PUNTOS_VISITANTE > P2.PUNTOS_LOCAL
GROUP BY P1.INICIO_TEMPORADA_P, P1.DIVISION_P
HAVING COUNT(*) > 3
ORDER BY P1.INICIO_TEMPORADA_P ASC;
