CREATE TABLE Estadio (
	Nombre		VARCHAR(50) PRIMARY KEY,
	Fecha_Inag 		NUMBER(4),
	Capacidad 		NUMBER(6)
);


CREATE TABLE Equipo (
	Nombre_Corto		VARCHAR(20) PRIMARY KEY,
	Nombre_Oficial	VARCHAR(50),
	Nombre_Historico	VARCHAR(50),
	Ciudad			VARCHAR(50),
	Fecha_fundacion	NUMBER(4),
	Nombre_e			VARCHAR(50),
	FOREIGN KEY(Nombre_e) REFERENCES Estadio(Nombre)
);


CREATE TABLE Otro_nombre (
	Otros_Nombres	VARCHAR(70) PRIMARY KEY,
	Nombre_Corto_o	VARCHAR(20),
	FOREIGN KEY(Nombre_Corto_o) REFERENCES Equipo(Nombre_Corto)
);


CREATE TABLE Temporada (
	Inicio_temporada	NUMBER(4) PRIMARY KEY
);


CREATE TABLE Liga (
	Division		VARCHAR(10)	PRIMARY KEY,
	Nombre_comercial	VARCHAR(50),
	Denominacion_oficial	VARCHAR(50)
);


CREATE TABLE Partido (
	Jornada		NUMBER(2),
	Puntos_local 		NUMBER(2) NOT NULL,
	Puntos_visitante	NUMBER(2) NOT NULL,
	Equipo_local		VARCHAR(20),
	Equipo_visitante	VARCHAR(20),
	Division_p		VARCHAR(10),
	Inicio_temporada_p	NUMBER(4),
	FOREIGN KEY (Equipo_local) REFERENCES Equipo(Nombre_Corto),
	FOREIGN KEY (Equipo_visitante) REFERENCES Equipo(Nombre_Corto),
	FOREIGN KEY (Division_p) REFERENCES Liga(Division),
	FOREIGN KEY (Inicio_temporada_p) REFERENCES Temporada(Inicio_temporada),
	PRIMARY KEY (Jornada, Equipo_local, Equipo_visitante, Division_p, Inicio_temporada_p)
);


CREATE VIEW Clasificacion AS
SELECT INICIO_TEMPORADA_P, DIVISION_P, EQUIPO, SUM(PUNTOS) AS PUNTOS_TOTALES, SUM(GOLES_RECIBIDOS) AS GOLES_RECIBIDOS
FROM (
    SELECT INICIO_TEMPORADA_P, DIVISION_P, EQUIPO_LOCAL AS EQUIPO, 3 AS PUNTOS, PUNTOS_VISITANTE AS GOLES_RECIBIDOS
    FROM PARTIDO
    WHERE PUNTOS_LOCAL > PUNTOS_VISITANTE
    UNION ALL
    SELECT INICIO_TEMPORADA_P, DIVISION_P, EQUIPO_VISITANTE AS EQUIPO, 3 AS PUNTOS, PUNTOS_LOCAL AS GOLES_RECIBIDOS
    FROM PARTIDO
    WHERE PUNTOS_VISITANTE > PUNTOS_LOCAL
    UNION ALL
    SELECT INICIO_TEMPORADA_P, DIVISION_P, EQUIPO_LOCAL AS EQUIPO, 1 AS PUNTOS, PUNTOS_VISITANTE AS GOLES_RECIBIDOS
    FROM PARTIDO
    WHERE PUNTOS_LOCAL = PUNTOS_VISITANTE
    UNION ALL
    SELECT INICIO_TEMPORADA_P, DIVISION_P, EQUIPO_VISITANTE AS EQUIPO, 1 AS PUNTOS, PUNTOS_LOCAL AS GOLES_RECIBIDOS
    FROM PARTIDO
    WHERE PUNTOS_VISITANTE = PUNTOS_LOCAL
)
GROUP BY INICIO_TEMPORADA_P, DIVISION_P, EQUIPO
ORDER BY INICIO_TEMPORADA_P ASC, DIVISION_P ASC, PUNTOS_TOTALES DESC, GOLES_RECIBIDOS ASC;
