SELECT CARRIERNAME, SUM(TOTALRETRASO)/COUNT(*) AS MEDIARETRASO
FROM (
	SELECT CARRIERNAME, SUM(DELAY) AS TOTALRETRASO FROM VUELO
	LEFT JOIN INCIDENCIA I1 ON I1.FLIGHTDATE_I = FLIGHTDATE AND I1.FLIGHTNUM_I = FLIGHTNUM AND I1.CRSDEPTIME_I = CRSDEPTIME
	LEFT JOIN RETRASO R1 ON I1.ID_INCIDENCE = R1.ID_INCIDENCE_R
	JOIN AEROLINEA ON CARRIERCODE = CARRIERCODE_A
	WHERE CARRIERCODE NOT IN (
		-- Seleccionamos las aerolineas que, al menos un dia, hayan realizado menos de 1000 vuelos
		SELECT DISTINCT CARRIERCODE_A FROM VUELO			
		GROUP BY CARRIERCODE_A, FLIGHTDATE
		HAVING COUNT(*) < 1000
	) AND (
		I1.ID_INCIDENCE IS NULL -- Si es nulo, no existe incidencia (Solo habra 1 entrada, por lo que la incluimos)
		OR R1.ID_INCIDENCE_R IS NOT NULL -- si existe, es un retraso, lo incluimos
		OR ( -- Solo puede ser una cancelacion o un desvio
			NOT EXISTS ( -- Si existe, es una cancelacion, no la incluimos
				SELECT ID_INCIDENCE_C
				FROM CANCELACION
				WHERE ID_INCIDENCE_C = I1.ID_INCIDENCE
			) -- Solo puede ser un desvio
			AND NOT EXISTS ( -- Si el vuelo ya tiene retrasos, no incluimos los desvios
				SELECT ID_INCIDENCE_R
				FROM RETRASO
				JOIN INCIDENCIA ON ID_INCIDENCE_R = ID_INCIDENCE
				WHERE I1.FLIGHTDATE_I = FLIGHTDATE_I AND I1.FLIGHTNUM_I = FLIGHTNUM_I AND I1.CRSDEPTIME_I = CRSDEPTIME_I
			) -- Solo tiene desvios
			AND I1.ID_INCIDENCE = ( -- Solo incluimos el desvio con mayor id (Para incluir solo 1)
				SELECT MAX(ID_INCIDENCE_D)
				FROM DESVIO
				JOIN INCIDENCIA ON ID_INCIDENCE_D = ID_INCIDENCE
				WHERE I1.FLIGHTDATE_I = FLIGHTDATE_I AND I1.FLIGHTNUM_I = FLIGHTNUM_I AND I1.CRSDEPTIME_I = CRSDEPTIME_I
				GROUP BY FLIGHTDATE_I, FLIGHTNUM_I, CRSDEPTIME_I
			)
		)
	)
	GROUP BY CARRIERNAME, FLIGHTDATE, FLIGHTNUM, CRSDEPTIME
)
GROUP BY CARRIERNAME
ORDER BY MEDIARETRASO;

